In [1]:
# Task Setup: Imports & Reproducibility
import numpy as np

# Set NumPy random seed to 42 for reproducibility
np.random.seed(42)
print("NumPy random seed set to 42.")


NumPy random seed set to 42.


In [2]:
# Task A: Matrix Generation
# Generate Matrix A of shape (4, 3) containing random integers in range [1, 10]
A = np.random.randint(1, 11, size=(4, 3))

# Generate Matrix B of shape (3, 5) containing random integers in range [1, 10]
B = np.random.randint(1, 11, size=(3, 5))

# Display Matrix A with clear label and .shape attribute
print("Matrix A:")
print(A)
print("Shape of Matrix A:", A.shape)

print("\n" + "="*50 + "\n")

# Display Matrix B with clear label and .shape attribute
print("Matrix B:")
print(B)
print("Shape of Matrix B:", B.shape)


Matrix A:
[[ 7  4  8]
 [ 5  7 10]
 [ 3  7  8]
 [ 5  4  8]]
Shape of Matrix A: (4, 3)


Matrix B:
[[ 8  3  6  5  2]
 [ 8  6  2  5  1]
 [10  6  9  1 10]]
Shape of Matrix B: (3, 5)


In [3]:
# Task B: Dimension Validation & Dot Product
# Programmatically validate that the inner dimensions match using an assertion
assert A.shape[1] == B.shape[0], f"Dimension Mismatch: A.shape[1] ({A.shape[1]}) != B.shape[0] ({B.shape[0]})"
print("Assertion Passed: Inner dimensions match (A.shape[1] == B.shape[0])!")

# Compute the matrix product C = A . B
C = np.dot(A, B)

# Display resulting Matrix C and verify shape is (4, 5)
print("\nResulting Matrix C (A . B):")
print(C)
print("Shape of Matrix C:", C.shape)

assert C.shape == (4, 5), f"Assertion Failed: Matrix C shape is {C.shape}, expected (4, 5)"
print("Assertion Passed: Matrix C shape verified as (4, 5).")


Assertion Passed: Inner dimensions match (A.shape[1] == B.shape[0])!

Resulting Matrix C (A . B):
[[168  93 122  63  98]
 [196 117 134  70 117]
 [160  99 104  58  93]
 [152  87 110  53  94]]
Shape of Matrix C: (4, 5)
Assertion Passed: Matrix C shape verified as (4, 5).


In [4]:
# Task C: Reductions & Summary Statistics
# Compute and display total sum of all elements in matrix C
total_sum = np.sum(C)
print("Total Sum of all elements in Matrix C (∑∑ C_ij):", total_sum)

print("\n" + "-"*50 + "\n")

# Compute and display row-wise sums (axis=1)
row_sums = np.sum(C, axis=1)
print("Row-wise sums (axis=1):", row_sums)

print("\n" + "-"*50 + "\n")

# Compute and display column-wise sums (axis=0)
col_sums = np.sum(C, axis=0)
print("Column-wise sums (axis=0):", col_sums)


Total Sum of all elements in Matrix C (∑∑ C_ij): 2188

--------------------------------------------------

Row-wise sums (axis=1): [544 634 514 496]

--------------------------------------------------

Column-wise sums (axis=0): [676 396 470 244 402]
